### PR TITLE
fix: disable authentication properly

### LINKED ISSUE #80: bug: Log Out option is redundant when using DISABLE_AUTH
When using DISABLE_AUTH, the log out button should be disabled / greyed out. Accidentally clicking on **logout** breaks my reverse proxy, I have to manually restart NGINx.

### PR DESCRIPTION
**Pull request by 9p4**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: Fixes #80

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: backend/app.js [hunk 1]
```diff
@@ -18,11 +18,13 @@ const app = express();
 app.use(logger("dev"));
 app.use(express.json());
 app.use(express.urlencoded({ extended: false }));
-app.use(
-  bearerToken({
-    headerKey: "Bearer",
-  })
-);
+if (process.env.ZU_DISABLE_AUTH === "true") {
```
Comment (dec0dOS) [inline backend/app.js:21]: Hey, @9p4.
Why did you disable the authorization header? That would break the standard authorization flow.

**Review by dec0dOS — CHANGES_REQUESTED** [review]

File: backend/app.js (hunk 1 above)
Comment (9p4) [reply backend/app.js]: Whoops, should be fixed now.

Comment (dec0dOS) [reply backend/app.js]: Thanks for the fast response! That makes sense now.

File: frontend/src/components/HomeLoggedOut/HomeLoggedOut.jsx [hunk 2]
```diff
@@ -6,10 +6,12 @@ import { useHistory } from "react-router-dom";
 function HomeLoggedOut() {
   const [, setLoggedIn] = useLocalStorage("loggedIn", false);
   const [, setToken] = useLocalStorage("token", null);
+  const [, setDisableAuth] = useLocalStorage("disableAuth", false);
   const history = useHistory();
   axios.get("/auth/login").then(function (response) {
     if (!response.data.enabled) {
```
Comment (dec0dOS) [inline frontend/src/components/HomeLoggedOut/HomeLoggedOut.jsx:12]: It would be useful to add the `else` part to set the `setDisableAuth` to `false` if the configuration on the server-side has been modified.

File: frontend/src/components/Bar/Bar.jsx [hunk 3]
```diff
@@ -72,69 +73,70 @@ function Bar() {
...
-                }
-
-                return component;
-              })}
-            </Menu>
-          </>
-        )}
+        {/* The filter removes all elements that are "true" or "false" */}
+        {loggedIn &&
+          menuItems.filter((e) => typeof e !== "boolean").length > 0 && (
```
Comment (dec0dOS) [inline frontend/src/components/Bar/Bar.jsx:78]: I'm trying to figure out the meaning of this filter. Could you explain, please?

Comment (9p4) [reply frontend/src/components/Bar/Bar.jsx:78]: In lines 50-54, we are adding the "log out" button if `disableAuth` is set to false. When that happens, the array will have a value of `false` instead. The reason for the check of the length is to remove the hamburger menu if there are no elements to be shown. Because the array will have a "false" in it instead of an object, it still counts as an element. This filter removes all boolean values to check the length.

If there's a better way to conditionally add an element to a list without messing with const/whatever, I would be glad to change it.

Comment (dec0dOS) [reply frontend/src/components/Bar/Bar.jsx:78]: That seems a better approach: https://2ality.com/2017/04/conditional-literal-entries.html

Comment (9p4) [reply frontend/src/components/Bar/Bar.jsx]: Applied!

File: frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx [hunk 4]
```diff
@@ -11,10 +13,22 @@ import { generateNetworkConfig } from "utils/NetworkConfig";
...
 function HomeLoggedIn() {
   const [networks, setNetworks] = useState([]);
+  const [, setLoggedIn] = useLocalStorage("loggedIn", false);
+  const [, setDisableAuth] = useLocalStorage("disableAuth", false);
+  const [token, setToken] = useLocalStorage("token", null);
 
   const classes = useStyles();
   const history = useHistory();
 
+  axios.get("/auth/login").then(function (response) {
```
Comment (dec0dOS) [inline frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx:23]: Seems to be that this would cause too many redundant requests 🤔

Comment (dec0dOS) [reply frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx:23]: There should be another way to fetch. I've tested a bit more and the result does not sound good. On the page load, it could fetch the `/login` endpoint even three or more times (on every HomeLoggedIn component rerender).
Screenshot 2022-06-12 at 16 18 35

Comment (dec0dOS) [reply frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx:23]: Screenshot 2022-06-12 at 16 21 35

Sorry for the late response. The linter should not throw the warring to accept the PR.

Comment (9p4) [reply frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx:23]: Would you be fine with removing the code that keeps on checking for the new status and only sets it on first launch? That would remove the redundant request issue but would require the user to clear localStorage if the auth mechanism changes (which shouldn't happen more than once anyway)

Comment (dec0dOS) [reply frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx:23]: Seems to be that the necessity to clean localStorage is the best tradeoff. It would be awesome if you could add some info in the docs about setting up the authentication proxy example and adding the notice about the localStorage clean on the ZU_DISABLE_AUTH toggle. 

Thanks!

**Comment by 9p4** [comment]
Should all be good now. I had to do this via the web interface on my phone so it might not be perfect but it should be correct. CI can corroborate.

**Comment by dec0dOS** [comment]
@9p4, that is great, thanks!
